// firmware/main/version.h - Auto-generated by CI/CD
#ifndef VERSION_H
#define VERSION_H

// This file is automatically generated by GitHub Actions
// Do not edit manually

#define FIRMWARE_VERSION "0.1.0-dev"
#define BUILD_TIMESTAMP "2025-01-31T10:00:00Z"
#define GIT_COMMIT "abc1234"
#define BUILD_NUMBER "1"

#endif // VERSION_H